'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SubSuppGPAwRecomm
	Implements IEquatable(Of SubSuppGPAwRecomm)

	Function Equals1(other as SubSuppGPAwRecomm) as Boolean Implements IEquatable(Of SubSuppGPAwRecomm).Equals
		
		 If DirectCast(Me, Object).Equals(DirectCast(other, Object)) Then
            Return True
        Else
			If {Me.YearId,other.YearId,Me.GradeId,other.GradeId,Me.StudentId,other.StudentId}.Any(Function(s) s = 0) Then 
				Return False
			End If
		    Return (Me.YearId = other.YearId) And(Me.GradeId = other.GradeId) And(Me.StudentId = other.StudentId)
		End If	
	
	End Function
    Public Property YearId As Integer
    Public Property GradeId As Integer
    Public Property StudentId As Integer
    Public Property GPA As Nullable(Of Double)
    Public Property YearRecommId As Integer
    Public Property CGPA As Nullable(Of Double)
    Public Property CumulativeRecommId As Nullable(Of Integer)
    Public Property Comment As String

    Public Overridable Property BatchEnrollment As BatchEnrollment
    Public Overridable Property Batch As Batch
    Public Overridable Property GPAwRecomm As GPAwRecomm
    Public Overridable Property Grade As Grade
    Public Overridable Property RecommendationType As RecommendationType
    Public Overridable Property RecommendationType1 As RecommendationType
    Public Overridable Property Student As Student
    Public Overridable Property TimeYear As TimeYear

End Class
